"""Phase 12.1 (Step 9 Phase 3 -> Step 10 -> Step 10.1 -> Step 11 ->
Step 12.1 authorization/security boundary implementation): TTS output
authorization.

Verifies that every TTS filesystem write -- explicit model-supplied
output_path AND the default auto-generated audio_cache path alike --
passes through the canonical Phase-3 general file-write authorization
primitive (``tools.file_tools._check_general_file_write``), and that an
existing file at the target path is NEVER deleted, truncated, or
otherwise destructively overwritten regardless of the authorization
outcome.

Uses the command-provider TTS backend (a portable ``python -c`` copy
command, same technique as test_tts_command_providers.py) so these tests
exercise the real _text_to_speech_single()/text_to_speech_tool() code
paths end-to-end without touching a real network TTS API.
"""

import json
import os
import shlex
import subprocess
import sys

import pytest

from tools.tts_tool import text_to_speech_tool, _text_to_speech_single


def _python_copy_command() -> str:
    interpreter = sys.executable
    return (
        f'"{interpreter}" -c "import shutil, sys; '
        f'shutil.copyfile(sys.argv[1], sys.argv[2])" '
        f'{{input_path}} {{output_path}}'
    )


def _command_tts_config():
    return {
        "provider": "my-command-tts",
        "providers": {
            "my-command-tts": {
                "type": "command",
                "command": _python_copy_command(),
                "output_format": "mp3",
            },
        },
    }


@pytest.fixture
def approvals():
    """Controllable approval callback, same channel as
    TestGeneralFileWriteApproval (tests/tools/test_file_write_safety.py)."""
    from tools.terminal_tool import set_approval_callback
    state = {"calls": [], "answer": "deny"}

    def cb(command, description, **kwargs):
        state["calls"].append({"command": command, "description": description, **kwargs})
        return state["answer"]

    set_approval_callback(cb)
    yield state
    set_approval_callback(None)


@pytest.fixture(autouse=True)
def _reset_session_approvals():
    """Each general-gate grant is session-scoped; start clean per test."""
    import tools.approval as A
    session_key = A.get_current_session_key()
    A.clear_session(session_key)
    yield
    A.clear_session(session_key)


def _run_tts(text, output_path, **kw):
    with pytest.MonkeyPatch.context() as mp:
        mp.setattr("tools.tts_tool._load_tts_config", lambda: _command_tts_config())
        mp.setattr("gateway.session_context.get_session_env", lambda *a, **k: "")
        raw = text_to_speech_tool(text, output_path=output_path, **kw)
    return json.loads(raw)


class TestExplicitOutputPathAuthorization:
    def test_explicit_output_path_requests_approval(self, tmp_path, approvals):
        approvals["answer"] = "once"
        target = str(tmp_path / "narration.mp3")
        res = _run_tts("hello", target)
        assert res.get("success"), res
        assert len(approvals["calls"]) == 1

    def test_explicit_output_path_denial_blocks_write(self, tmp_path, approvals):
        target = tmp_path / "narration.mp3"
        approvals["answer"] = "deny"
        res = _run_tts("hello", str(target))
        assert not res.get("success"), res
        assert "BLOCKED" in (res.get("error") or "")
        assert not target.exists()

    def test_new_target_creation_succeeds_with_approval(self, tmp_path, approvals):
        approvals["answer"] = "once"
        target = tmp_path / "brand_new.mp3"
        res = _run_tts("hello", str(target))
        assert res.get("success"), res
        assert os.path.isfile(res["file_path"])


class TestDefaultAutoGeneratedPathAuthorization:
    """Ed's explicit Step 12.1 scoping decision: the default (no
    output_path) auto-generated audio_cache write must ALSO be gated --
    omitting output_path must not be an authorization bypass."""

    def test_default_path_requests_approval(self, approvals):
        approvals["answer"] = "once"
        res = _run_tts("hello", None)
        assert res.get("success"), res
        assert len(approvals["calls"]) == 1

    def test_default_path_denial_blocks_write(self, approvals):
        approvals["answer"] = "deny"
        res = _run_tts("hello", None)
        assert not res.get("success"), res
        assert "BLOCKED" in (res.get("error") or "")


class TestExistingFileNeverDestroyed:
    """The core Phase 12.1 fix: an existing file at the target is never
    deleted or truncated, regardless of whether authorization is granted
    or denied."""

    def test_existing_target_survives_denial(self, tmp_path, approvals):
        target = tmp_path / "existing.mp3"
        target.write_bytes(b"PRE-EXISTING AUDIO BYTES")
        approvals["answer"] = "deny"
        res = _run_tts("hello", str(target))
        assert not res.get("success"), res
        assert target.read_bytes() == b"PRE-EXISTING AUDIO BYTES", (
            "existing file must be byte-for-byte unchanged on denial"
        )

    def test_existing_target_survives_approval_via_free_path(self, tmp_path, approvals):
        """When authorization is GRANTED for a path that already has a
        file, the write must never clobber that file -- it must resolve
        to a new, non-colliding sibling path instead (matching Flux's
        _free_path pattern), per the Step 12.1 explicit requirement that
        authorization alone does not make destructive overwrite safe."""
        target = tmp_path / "existing.mp3"
        target.write_bytes(b"PRE-EXISTING AUDIO BYTES")
        approvals["answer"] = "once"
        res = _run_tts("hello", str(target))
        assert res.get("success"), res
        assert target.read_bytes() == b"PRE-EXISTING AUDIO BYTES", (
            "existing file must never be silently overwritten even when "
            "the write is approved"
        )
        written_path = res["file_path"]
        assert os.path.abspath(written_path) != os.path.abspath(str(target)), (
            "the actual write must land on a resolved sibling path, not "
            "the original occupied target"
        )
        assert os.path.isfile(written_path)


class TestNoHumanChannelFailClosed:
    def test_no_callback_registered_fails_closed(self, tmp_path):
        """No CLI callback, no gateway notify bound: TTS write must be
        BLOCKED, never silently allowed."""
        from tools.terminal_tool import set_approval_callback
        set_approval_callback(None)
        target = tmp_path / "unattended.mp3"
        res = _run_tts("hello", str(target))
        assert not res.get("success"), res
        assert "BLOCKED" in (res.get("error") or "")
        assert not target.exists()


class TestYoloDoesNotBypass:
    def test_yolo_frozen_still_requires_approval(self, tmp_path, approvals, monkeypatch):
        """The whole point: auto-approve/yolo must NOT bypass the TTS
        general-file-write gate, mirroring the write_file/patch guarantee."""
        import tools.approval as A
        monkeypatch.setattr(A, "_YOLO_MODE_FROZEN", True)
        target = tmp_path / "yolo_test.mp3"
        approvals["answer"] = "deny"
        res = _run_tts("hello", str(target))
        assert not res.get("success"), res
        assert "BLOCKED" in (res.get("error") or "")
        assert not target.exists()
        assert len(approvals["calls"]) == 1, "yolo bypassed the TTS write gate"


class TestApprovalsModeOffDoesNotBypass:
    def test_approvals_mode_off_still_requires_approval(self, tmp_path, approvals, monkeypatch):
        """approvals.mode=off (the config-level yolo-equivalent) is a
        terminal/execute_code approval-mode setting and must have no
        effect on the general file-write gate that TTS now reuses."""
        import tools.approval as approval_mod
        monkeypatch.setattr(approval_mod, "_get_approval_mode", lambda: "off")
        target = tmp_path / "approvals_off_test.mp3"
        approvals["answer"] = "deny"
        res = _run_tts("hello", str(target))
        assert not res.get("success"), res
        assert "BLOCKED" in (res.get("error") or "")
        assert not target.exists()


class TestTraversalStillBlocked:
    def test_traversal_rejected_before_authorization(self, tmp_path, approvals):
        """Path-traversal rejection is a separate, earlier check than the
        general-file-write gate and must remain effective; it must fire
        without even reaching the approval callback."""
        approvals["answer"] = "once"
        res = _run_tts("hello", "audio/../../etc/cron.d/x")
        assert not res.get("success"), res
        assert "traversal" in (res.get("error") or "").lower()
        assert len(approvals["calls"]) == 0, (
            "traversal must be rejected before the approval gate is ever consulted"
        )


class TestAbsolutePathBehavior:
    def test_absolute_path_is_honored_and_authorized(self, tmp_path, approvals):
        approvals["answer"] = "once"
        target = tmp_path / "abs" / "out.mp3"
        res = _run_tts("hello", str(target))
        assert res.get("success"), res
        assert os.path.isabs(res["file_path"])


class TestFinalResolvedPathMatchesAuthorizedPath:
    def test_authorized_path_is_exactly_the_written_path(self, tmp_path, approvals, monkeypatch):
        """The authorization decision must correspond to the EXACT path
        that ends up on disk -- never a further-transformed path."""
        captured = {}
        from tools import file_tools as ft
        original = ft._check_general_file_write

        def spy(paths, task_id="default"):
            captured["paths"] = list(paths)
            return original(paths, task_id)

        monkeypatch.setattr(ft, "_check_general_file_write", spy)
        # tts_tool imports the function locally inside _tts_authorize_destination,
        # so patch the source module -- the local `from tools.file_tools import
        # _check_general_file_write` re-resolves it from tools.file_tools each call.
        approvals["answer"] = "once"
        target = tmp_path / "match_check.mp3"
        res = _run_tts("hello", str(target))
        assert res.get("success"), res
        assert captured.get("paths") == [res["file_path"]], (
            "the path passed to the authorization primitive must be "
            "identical to the path actually written"
        )


class TestEveryBackendCovered:
    """Every TTS backend receives its path from the single choke point in
    _text_to_speech_single()/text_to_speech_tool() -- this class asserts
    that invariant directly rather than re-testing each backend's network
    call, which the existing provider-specific test files already mock
    and cover independently (test_tts_speed.py, etc.)."""

    def test_synthesize_with_command_provider_no_longer_deletes(self, tmp_path):
        """Direct regression test for the removed unlink(): calling the
        command-provider backend on an existing target must not delete
        it as a side effect of the backend itself (that responsibility
        now lives entirely in the caller's pre-authorized _tts_free_path
        resolution, never in this function)."""
        from tools.tts_tool import _generate_command_tts
        target = tmp_path / "backend_direct.mp3"
        target.write_bytes(b"SENTINEL")
        config = {
            "command": _python_copy_command(),
            "output_format": "mp3",
        }
        # Feed the backend a *different*, non-colliding path (as the
        # caller now always does) -- confirms the backend itself performs
        # no existence check/deletion of its own.
        other = tmp_path / "backend_direct-2.mp3"
        _generate_command_tts(
            "hello", str(other), "my-command-tts", config, {},
        )
        assert target.read_bytes() == b"SENTINEL", (
            "the command-provider backend must never touch an unrelated "
            "existing file"
        )
        assert other.exists()

    def test_single_chunk_helper_forwards_task_id(self, tmp_path, approvals, monkeypatch):
        """_text_to_speech_single accepts and uses task_id for scope-correct
        authorization -- NeuTTS and every other backend inherit this via
        the same single path-resolution point, so this one test covers
        the invariant for all of them."""
        monkeypatch.setattr("tools.tts_tool._load_tts_config", lambda: _command_tts_config())
        monkeypatch.setattr("gateway.session_context.get_session_env", lambda *a, **k: "")
        approvals["answer"] = "once"
        target = tmp_path / "task_scoped.mp3"
        raw = _text_to_speech_single(
            "hello", str(target), tts_config_override=_command_tts_config(),
            task_id="my-task-42",
        )
        res = json.loads(raw)
        assert res.get("success"), res


class TestSessionTaskSubagentAuthorizationScope:
    """Mirrors tests/tools/test_authorization_scope_phase3.py's task
    isolation guarantee, applied to the TTS gate specifically."""

    def test_grant_under_one_task_does_not_satisfy_another_task(self, tmp_path, approvals, monkeypatch):
        import tools.approval as A
        monkeypatch.setattr("tools.tts_tool._load_tts_config", lambda: _command_tts_config())
        monkeypatch.setattr("gateway.session_context.get_session_env", lambda *a, **k: "")

        session_key = A.get_current_session_key()
        tokens_a = A.set_current_authorization_scope(session_key, task_id="task-A")
        approvals["answer"] = "once"
        target_a = tmp_path / "task_a.mp3"
        try:
            res_a = json.loads(_text_to_speech_single(
                "hello", str(target_a), tts_config_override=_command_tts_config(),
                task_id="task-A",
            ))
        finally:
            A.reset_current_authorization_scope(tokens_a)
        assert res_a.get("success"), res_a

        tokens_b = A.set_current_authorization_scope(session_key, task_id="task-B")
        approvals["answer"] = "deny"
        target_b = tmp_path / "task_b.mp3"
        try:
            res_b = json.loads(_text_to_speech_single(
                "hello", str(target_b), tts_config_override=_command_tts_config(),
                task_id="task-B",
            ))
        finally:
            A.reset_current_authorization_scope(tokens_b)
        assert not res_b.get("success"), (
            "a grant scoped to task-A must not satisfy a write requested "
            "under task-B"
        )
